# Generated by Django 4.0.5 on 2022-07-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='update_dt',
            new_name='updated_dt',
        ),
    ]
