# Generated by Django 4.0.5 on 2022-07-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_update_dt_review_updated_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetImg',
            fields=[
                ('target_img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50)),
                ('pixel_x', models.IntegerField()),
                ('pixel_y', models.IntegerField()),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ResultText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('axis_x', models.IntegerField()),
                ('axis_y', models.IntegerField()),
                ('text', models.TextField()),
                ('result_txt_id', models.ForeignKey(db_column='target_img_id', on_delete=django.db.models.deletion.CASCADE, to='mainApp.targetimg')),
            ],
        ),
    ]
