# Generated by Django 4.0.5 on 2022-07-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_resulttext_image_alter_targetimg_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultText',
        ),
        migrations.DeleteModel(
            name='TargetImg',
        ),
    ]
