# Generated by Django 4.0.5 on 2022-07-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetImg',
            fields=[
                ('target_img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50)),
                ('pixel_x', models.IntegerField()),
                ('pixel_y', models.IntegerField()),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
    ]
